version: '3.8'

services:
  backend:
    image: maverick11471/bibid-back:1.0
    container_name: docker-bibid-back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/bibid.store/fullchain.pem:/etc/letsencrypt/live/bibid.store/fullchain.pem
      - /etc/letsencrypt/live/bibid.store/privkey.pem:/etc/letsencrypt/live/bibid.store/privkey.pem
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD="!dkdlxl1234"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "!dkdlxl1234"]
