version: '3.8'

services:
  backend:
    build:
      context: .              # 현재 디렉토리에서 Dockerfile을 참조
      dockerfile: Dockerfile   # 루트에 있는 Dockerfile 사용
    ports:
      - "8080:8080"            # 백엔드 포트 매핑
    environment:
      - SPRING_REDIS_HOST=redis  # Redis 호스트 설정 (서비스 이름)
      - SPRING_REDIS_PORT=6379   # Redis 포트 설정
      - SPRING_REDIS_PASSWORD=!dkdlxl1234  # Redis 비밀번호 설정
    depends_on:
      - redis                  # Redis가 먼저 실행되도록 설정

  redis:
    image: redis:latest
    ports:
      - "6379:6379"            # Redis 포트 매핑
    command: ["redis-server", "--requirepass", "!dkdlxl1234"]  # 비밀번호 설정
